//
// Created by Isini on 1/24/2022.
//

#ifndef FLEXIBLECOMPUTERLANGUAGE_TESTLISTREMOVEFROMSTART_H
#define FLEXIBLECOMPUTERLANGUAGE_TESTLISTREMOVEFROMSTART_H


class TestRemoveElement {

public:
    static void TestListRunRemoveElement();

};


#endif //FLEXIBLECOMPUTERLANGUAGE_TESTLISTREMOVEFROMSTART_H
