//
// Created by User on 1/26/2022.
//

#ifndef FLEXIBLECOMPUTERLANGUAGE_TESTLISTGETPREFIX_H
#define FLEXIBLECOMPUTERLANGUAGE_TESTLISTGETPREFIX_H


class TestListGetPrefix {
public:
    static void runTest();

};


#endif //FLEXIBLECOMPUTERLANGUAGE_TESTLISTGETPREFIX_H
