//
// Created by Isini Dananjana on 1/24/2022.
//

#ifndef FLEXIBLECOMPUTERLANGUAGE_TESTLISTGETLASTELEM_H
#define FLEXIBLECOMPUTERLANGUAGE_TESTLISTGETLASTELEM_H


class TestListGetLastElem {

public:
    static void TestListGetLastElemet();

};


#endif //FLEXIBLECOMPUTERLANGUAGE_TESTLISTGETLASTELEM_H
